server:
  port: 8082
databases:
  - user: admin
    password: admin
    host: localhost
    dbName: shopDev
  - user: order
    password: admin
    host: localhost
    dbName: order
security:
  jwt:
    key: abc123